services:
  app:
    build: .
    container_name: fastapi_auth_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app                  # mounts local code → hot reload works
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy    # waits until postgres is ready
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: fastapi_auth_db
    ports:
      - "5432:5432"             # expose so you can connect via DBeaver/pgAdmin
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data    # persists data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fastapi_auth_redis
    ports:
      - "6379:6379"      # expose so you can connect via RedisInsight
    volumes:
        - redis_data:/data    # persists data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: